In [2]:
import pandas as pd   # Import pandas for data manipulation
from datetime import timedelta   # Import timedelta for time calculations

ModuleNotFoundError: No module named 'pandas'

In [ ]:
data =  pd.read_excel('Assignment_Timecard.xlsx') # Load timecard data from Excel file

In [3]:
data.columns  # View column names
data = data.drop(['Unnamed: 9','Unnamed: 10'],axis=1) # Drop unnecessary columns

In [4]:
data.head(20) # Preview the first 20 rows

,Position ID,Position Status,Time,Time Out,Timecard Hours (as Time),Pay Cycle Start Date,Pay Cycle End Date,Employee Name,File Number
0,WFS000054,Active,NaT,NaT,NaN,NaT,NaT,"SiWgh, PraGhjEM",54
1,WFS000065,Active,2023-09-12 10:08:00,2023-09-12 13:53:00,3:45,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65
2,WFS000065,Active,2023-09-12 14:23:00,2023-09-12 19:02:00,4:39,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65
3,WFS000065,Active,2023-09-13 10:08:00,2023-09-13 14:20:00,4:12,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65
4,WFS000065,Active,2023-09-13 14:50:00,2023-09-13 20:44:00,5:54,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65
5,WFS000065,Active,2023-09-14 10:09:00,2023-09-14 14:30:56,4:21,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65
6,WFS000065,Active,2023-09-14 15:00:52,2023-09-14 19:14:00,4:14,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65
7,WFS000065,Active,2023-09-15 10:11:00,2023-09-15 14:41:00,4:30,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65
8,WFS000065,Active,2023-09-15 15:11:00,2023-09-15 19:05:00,3:54,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65
9,WFS000065,Active,2023-09-16 09:51:00,2023-09-16 14:50:48,4:59,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65
10,WFS000065,Active,2023-09-16 15:20:39,2023-09-16 20:19:00,4:59,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65
11,WFS000065,Active,2023-09-19 09:55:00,2023-09-19 13:56:00,4:01,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65
12,WFS000065,Active,2023-09-19 14:26:00,2023-09-19 18:29:00,4:03,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65
13,WFS000065,Active,2023-09-20 09:54:00,2023-09-20 14:12:00,4:18,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65
14,WFS000065,Active,2023-09-20 14:42:00,2023-09-20 18:46:00,4:04,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65
15,WFS000065,Active,2023-09-21 09:55:00,2023-09-21 14:03:00,4:08,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65
16,WFS000065,Active,2023-09-21 14:33:00,2023-09-21 18:47:00,4:14,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65
17,WFS000065,Active,2023-09-22 09:55:00,2023-09-22 14:50:15,4:55,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65
18,WFS000065,Active,2023-09-22 15:20:09,2023-09-22 20:26:00,5:06,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65
19,WFS000065,Active,2023-09-23 09:55:00,2023-09-23 15:47:00,6:52,2023-09-10,2023-09-23,"REsaXiaWE, XAis",65

In [5]:
# Define a function to check for seven consecutive days of work
dic = {}

for index, row in data.iterrows():
    key = (row['Position ID'], row['Employee Name'])
    if key not in dic:
        dic[key] = []
    dic[key].append(row)
    # print(row['Position ID'])

In [ ]:

# Define a function to check for seven consecutive days of work
def check_seven_consecutive_days(date_list):
    if pd.isnull(date_list[0]):
        return False
    date_ints = [date.toordinal() for date in date_list]
    date_ints.sort()  # Sort chronologically
    counter = 1 # Initialize a counter
    prev_date = date_ints[0]
    
    for date in date_ints[1:]:
        if date - prev_date == 1:  # Check for consecutive days
            counter += 1
        else:
            counter = 1
            
        if counter >= 7:  # Found seven consecutive days
            return True
        
        prev_date = date
    return False

In [8]:
# Identify employees who worked seven consecutive days
list_of_people_working_seven_consecutive_days = []

for i in dic:
    date_list = [row['Time'] for row in dic[i]]
    if check_seven_consecutive_days(date_list):
        list_of_people_working_seven_consecutive_days.append(i)

In [9]:
# Print results for consecutive days
print("List of people who has worked seven consecutive days")
print(len(list_of_people_working_seven_consecutive_days))
list_of_people_working_seven_consecutive_days

List of people who has worked seven consecutive days
0

[]

In [ ]:
# Identify employees with short breaks between shifts
list_of_people_from_one_to_ten = []
for i in dic:
    date_list = [row['Time'] for row in dic[i]]
    for j in range(len(date_list)-1):
        diff = date_list[j+1] - date_list[j]
        diff = (diff.seconds / 60)/60 # Convert timedelta to hours
        if 1 < diff < 10:
            list_of_people_from_one_to_ten.append(i)
            break

In [11]:
# Print results for short breaks
print("List of people who has taken less than 10 hours but more than 1 hours between shifts")
print(len(list_of_people_from_one_to_ten))
list_of_people_from_one_to_ten

List of people who has taken less than 10 hours but more than 1 hours between shifts
96

[('WFS000065', 'REsaXiaWE, XAis'),
 ('WFS000101', 'Sparks, KeWWeMh'),
 ('WFS000127', 'GaXCes, EXias XEpez'),
 ('WFS000153', 'CaMaXaWE, CeghaW'),
 ('WFS000170', 'Arias, FeXipe'),
 ('WFS000180', 'Merrazas, GriaW'),
 ('WFS000181', 'GarWes, JAsMiW'),
 ('WFS000183', 'FeXix, XeEWeX'),
 ('WFS000185', 'HerCEsiXXE, PedrE'),
 ('WFS000200', 'Xee, XaCar'),
 ('WFS000226', 'GaWks, GryaW'),
 ('WFS000228', 'MAake, CasiaWE'),
 ('WFS000246', 'SiWgh, MarAWpreeM'),
 ('WFS000268', 'DiWh, DaA'),
 ('WFS000306', 'ArEsMigAi, AXexaWder'),
 ('WFS000318', 'De Xa Cerda, IgWaciE'),
 ('WFS000336', 'REdrigAez, PedrE'),
 ('WFS000345', 'MraW, WiXXiaC Ha'),
 ('WFS000360', 'MAcker, CichaeX'),
 ('WFS000362', 'CaMXEck, CEhaCCed'),
 ('WFS000364', 'MaXeGi, ACirCasEAd'),
 ('WFS000368', 'PayaW, DaWieX'),
 ('WFS000372', 'ErMiz, AGigaiX'),
 ('WFS000382', 'ErEpeza, JEvaW'),
 ('WFS000391', 'VasqAez, AXfredE'),
 ('WFS000393', 'SavaWg, JEhW'),
 ('WFS000412', 'REdrigAez, XAis'),
 ('WFS000414', 'EasMCaW, CichaeX'),
 ('WFS000418', 'SiWgh, CaWpreeM'),
 ('WFS000420', 'RECerE, SergiE'),
 ('WFS000424', 'SiWgh, JaspreeM'),
 ('WFS000426', 'SiWgXeMEW, REger'),
 ('WFS000434', 'PaXaciE, JEWaMhaW'),
 ('WFS000442', 'ErEzcE, SaAX'),
 ('WFS000446', 'CercadE, SaAX'),
 ('WFS000456', 'CEreira Jr, JEse'),
 ('WFS000457', 'AXvarez, Edgar'),
 ('WFS000460', 'PaAXE, KyXe'),
 ('WFS000462', 'XiWW, JAsMiW'),
 ('WFS000463', 'CaXdEWadE, AXfEWsE'),
 ('WFS000465', 'CeWdEza, Erik'),
 ('WFS000469', 'PerkiWs, MarraWce'),
 ('WFS000473', 'GAeWdia, JAaW CarXEs'),
 ('WFS000477', 'ZaCEra, Edward'),
 ('WFS000491', 'ArevaXE, JEse'),
 ('WFS000495', 'CErMes, DEAgXas Farid'),
 ('WFS000496', 'CercadE, CrisMiaW'),
 ('WFS000499', 'ZaCEra, CigAeX'),
 ('WFS000500', 'Caxies, MerreXX'),
 ('WFS000501', 'CcRAWWeX, REWaXd Xee'),
 ('WFS000503', 'CEMMa, Jessica'),
 ('WFS000505', 'REdrigAez, AXexis GAMierrez'),
 ('WFS000507', 'Rivera AXcaWMar, GrayaW'),
 ('WFS000508', 'EXivares, FeXCaW'),
 ('WFS000509', 'ChaCErE, HEXger CarMiWez'),
 ('WFS000511', 'WiXXiaCs, MyrreXX'),
 ('WFS000514', 'CaraGiXXa, AWMhEWy'),
 ('WFS000515', 'GrACfieXd, CErWeXiAs'),
 ('WFS000517', 'Perez, EdwiW JiCeWez'),
 ('WFS000518', 'ArrAMia, AXexis ArMArE'),
 ('WFS000519', 'DiXXard, JEwaWW Cedric'),
 ('WFS000521', 'SaWchez PaCpXEWa, CrisMiaW AXGerM'),
 ('WFS000522', 'XEpez WAWez, XAis'),
 ('WFS000523', 'DeXgadiXXE REdarMe, ChrisMiaW S'),
 ('WFS000528', 'CeciWa, SiXvesMre Jr'),
 ('WFS000530', 'FaGiaW CiraWda, JEse'),
 ('WFS000536', 'HaCiXMEW, DeaWMe DevEW'),
 ('WFS000538', 'HAWMer, ViWceWM De PaAX'),
 ('WFS000541', 'AXcEcer, ECar JesAs'),
 ('WFS000546', 'IWGEAa, JeffersEW'),
 ('WFS000548', 'CesiWa CEreWE, KeviW FaGiaW'),
 ('WFS000549', 'HEGGie ErMega, SeGasMiaW CichaeX'),
 ('WFS000550', 'REdrigAez, GraWdEW AWgeX'),
 ('WFS000551', 'Diaz GaXvez, RicardE JEsAe'),
 ('WFS000552', 'EsMrada, JEse FeXix'),
 ('WFS000555', 'SMrickXaWd, REdWey EAgeWe'),
 ('WFS000556', 'RAvaXcaGa GaWAeXEs, DaWieX JesAs'),
 ('WFS000557', 'JerEWiCE CEraXes, CarXEs D'),
 ('WFS000566', 'CharXes, EGadiah SEraccE Jr'),
 ('WFS000569', 'DECiWgAez AviWa, CigAeX AWgeX'),
 ('WFS000571', 'CAevas ZavaXa, JErge XAis'),
 ('WFS000572', 'XariEs XaWdaverde, XAis ErWesME'),
 ('WFS000573', 'VaXderraCa CasMiXXE, Escar FaGiaW'),
 ('WFS000574', 'CiGriaW DeXgadE, EXeWa S'),
 ('WFS000576', 'CarMer, XyWWeXX DejAaW Jr'),
 ('WFS000577', 'SaWchez, ArWAXfE'),
 ('WFS000578', 'VasqAez, JEhW SeGasMiaW'),
 ('WFS000579', 'GAMierrez, PedrE CigAeX'),
 ('WFS000581', 'HerWaWdez SaWchez, AWdrew AWMhEWy'),
 ('WFS000582', 'De XEs SaWMEs, JEseph XAis'),
 ('WFS000583', 'ViXXa, AXfredE AieXXE'),
 ('WFS000584', 'ArCeWMa FXEres, JEWaMhaW'),
 ('WFS000585', 'RaCEs HerWaWdez, AdieX ECar'),
 ('WFS000587', 'XariEs, Cesar GiEvaWWi'),
 ('WFS000588', 'AGeX, WaMhaW REGerM PeWa'),
 ('WFS000589', 'WgAyeW, RayCEWd')]

In [12]:
# Identify employees who worked long shifts
list_of_people_working_14_hrs = []
for i in dic:
    in_date = [row['Time'] for row in dic[i]]
    out_date = [row['Time Out'] for row in dic[i]]
    if pd.isnull(in_date[0]):
        continue    # Skip if missing data
    for j in range(len(in_date)):
        diff = out_date[j] - in_date[j]
        diff = (diff.seconds / 60)/60  
        if diff > 14:
            list_of_people_working_14_hrs.append(i)
            break

In [13]:
# Print results for long shifts
print("List of people who has worked for more than 14 hours in a single shift")
print(len(list_of_people_working_14_hrs))
list_of_people_working_14_hrs

List of people who has worked for more than 14 hours in a single shift
1

[('WFS000523', 'DeXgadiXXE REdarMe, ChrisMiaW S')]